- name: Install root certificate authorities
  pkgng:
    name: 'ca_root_nss'
    state: present
  register: pkg_result
  until: pkg_result is succeeded

- name: Add network config
  lineinfile:
    backup: '{{ jail_backup_old_files }}'
    dest: '/etc/rc.conf'
    state: present
    line: '{{ ifconfig_net_if_line }}'

- name: Add jail name to /etc/hosts
  lineinfile:
    backup: '{{ jail_backup_old_files }}'
    dest: '{{ jail_home.stdout }}/etc/hosts'
    state: present
    regexp: '^{{ jail_net_ip }}'
    line: '{{ jail_net_ip }}  {{ jail_name }}'
